set(_AMENT_PACKAGE_NAME "linglong_control")
set(linglong_control_VERSION "0.3.0")
set(linglong_control_MAINTAINER "Linglong developer <maintainer@example.com>")
set(linglong_control_BUILD_DEPENDS "hardware_interface" "pluginlib" "rclcpp" "rclcpp_lifecycle")
set(linglong_control_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(linglong_control_BUILD_EXPORT_DEPENDS "hardware_interface" "pluginlib" "rclcpp" "rclcpp_lifecycle")
set(linglong_control_BUILDTOOL_EXPORT_DEPENDS )
set(linglong_control_EXEC_DEPENDS "arm_control" "controller_manager" "controller_manager_msgs" "joint_state_broadcaster" "joint_trajectory_controller" "rclpy" "std_msgs" "std_srvs" "rcl_interfaces" "control_msgs" "trajectory_msgs" "action_msgs" "diagnostic_msgs" "launch" "launch_ros" "ament_index_python" "robot_state_publisher" "rviz2" "xacro" "python3-yaml" "rosbag2" "hardware_interface" "pluginlib" "rclcpp" "rclcpp_lifecycle")
set(linglong_control_TEST_DEPENDS "ament_cmake_pytest" "ament_cmake_gtest" "python3-pytest" "python3-yaml")
set(linglong_control_GROUP_DEPENDS )
set(linglong_control_MEMBER_OF_GROUPS )
set(linglong_control_DEPRECATED "")
set(linglong_control_EXPORT_TAGS)
list(APPEND linglong_control_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
